Traceback (most recent call last):
  File "/Users/ryotakusakai/opt/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ryotakusakai/opt/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ryotakusakai/opt/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/ryotakusakai/opt/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/ryotakusakai/opt/anaconda3/envs/jupyterbook/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/ryotakusakai/opt/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/ryotakusakai/opt/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ryotakusakai/opt/anaconda3/envs/jupyterbook/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import math #sqrt(square root)関数を使うための1行
s = [1,4,16,-25,36,49,64,81,100,121,144]
#for i in range(20):
for i in s:
    print(math.sqrt(i)) 
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[11], line 5[0m
[1;32m      3[0m [38;5;66;03m#for i in range(20):[39;00m
[1;32m      4[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m s:
[0;32m----> 5[0m     [38;5;28mprint[39m([43mmath[49m[38;5;241;43m.[39;49m[43msqrt[49m[43m([49m[43mi[49m[43m)[49m) 

[0;31mValueError[0m: math domain error
ValueError: math domain error

